dist:
  module: github.com/open-telemetry/opentelemetry-collector-builder # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  description: "OpenTelemetry Collector for Honeycomb" # a long name for the application. Optional.
  include_core: true # whether the core components should be included in the distribution. Optional.
  otelcol_version: "0.33.0" # the OpenTelemetry Collector version to use as base for the distribution. Optional.
  output_path: build # the path to write the output (sources and binary). Optional.
  go: "/usr/bin/go" # which Go binary to use to compile the generated sources. Optional.
receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.33.0"
processors:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.33.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.33.0"
  - gomod: "github.com/honeycombio/opentelemetry-collector-configs/timestampprocessor v0.0.0"
    path: ./timestampprocessor
replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod
  # these are necessary because of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1217
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/common => github.com/open-telemetry/opentelemetry-collector-contrib/internal/common v0.33.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/interval => github.com/open-telemetry/opentelemetry-collector-contrib/internal/interval v0.33.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig => github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig v0.33.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/kubelet => github.com/open-telemetry/opentelemetry-collector-contrib/internal/kubelet v0.33.0
  # necessary for version 0.33.0:
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver => github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.33.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver => github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.33.0
