version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: maxedmandshny/cci-go-yq:0.0.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test
