version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: maxedmandshny/cci-go-yq:0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - builder-config-{{ checksum "builder-config.yaml" }}
      - run:
          name: Run tests
          command: make test
      - run:
          name: Create artifacts
          command: |
            make;
            mkdir /home/circleci/project/artifacts; 
            cp ./build/otelcol-hny /home/circleci/project/artifacts/.;
      - save_cache:
          key: builder-config-{{ checksum "builder-config.yaml" }}
          paths: build
      - store_artifacts:
          path: /home/circleci/project/artifacts/
      - store_artifacts:
          path: /home/circleci/project/artifacts/otelcol-hny
